import requests
from pprint import pprint

url = 'http://localhost:8000'


def start(user, problem, count):
    uri = url + '/start' + '/' + user + '/' + str(problem) + '/' + str(count)
    return requests.post(uri).json()


def oncalls(token):
    uri = url + '/oncalls'
    return requests.get(uri, headers={'X-Auth-Token': token}).json()


def action(token, cmds):
    uri = url + '/action'
    return requests.post(uri, headers={'X-Auth-Token': token}, json={'commands': cmds}).json()


def p0_simulator():
    user = 'tester'
    problem = 0
    count = 2

    ret = start(user, problem, count)
    token = ret['token']
    pprint('Token for %s is %s' % (user, token))

    # res = oncalls(token)
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'UP'}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'UP'}, {'elevator_id': 1, 'command': 'OPEN'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'UP'}, {'elevator_id': 1, 'command': 'ENTER', 'call_ids': [2, 3]}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'STOP'}, {'elevator_id': 1, 'command': 'CLOSE'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'OPEN'}, {'elevator_id': 1, 'command': 'UP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'ENTER', 'call_ids': [0, 1]}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'CLOSE'}, {'elevator_id': 1, 'command': 'OPEN'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'DOWN'}, {'elevator_id': 1, 'command': 'EXIT', 'call_ids': [2]}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'STOP'}, {'elevator_id': 1, 'command': 'CLOSE'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'OPEN'}, {'elevator_id': 1, 'command': 'UP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'EXIT', 'call_ids': [1]}, {'elevator_id': 1, 'command': 'UP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'CLOSE'}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'DOWN'}, {'elevator_id': 1, 'command': 'OPEN'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'STOP'}, {'elevator_id': 1, 'command': 'EXIT', 'call_ids': [3]}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'OPEN'}, {'elevator_id': 1, 'command': 'CLOSE'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'ENTER', 'call_ids': [4]}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'CLOSE'}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'DOWN'}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'STOP'}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'OPEN'}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'EXIT', 'call_ids': [0, 4]}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'ENTER', 'call_ids': [5]}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'CLOSE'}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'UP'}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'STOP'}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'OPEN'}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    res = oncalls(token)
    pprint(res)
    response = action(token, [{'elevator_id': 0, 'command': 'EXIT', 'call_ids': [5]}, {'elevator_id': 1, 'command': 'STOP'}])
    print('action')
    pprint(response)
    print("============================================================================")
    print("fin")
    res = oncalls(token)
    pprint(res)
if __name__ == '__main__':
    p0_simulator()
